# dart run package_rename
package_rename_config:
  android:
    app_name: It Geeks
    package_name: com.itgeeks.mobilify
    # override_old_package: com.itg.golime

  ios:
    app_name: It Geeks
    bundle_name: com.itgeeks.mobilify
    package_name: com.itgeeks.mobilify

  web:
    app_name: It Geeks
    description: com.itgeeks.mobilify

  linux:
    app_name: It Geeks
    package_name: com.itgeeks.mobilify
    exe_name: renamedemo-linux-x64

  windows:
    app_name: It Geeks
    organization: NT
    copyright_notice: Copyright © 2024 NT. All rights reserved.
    exe_name: renamedemo-win32

  macos:
    app_name: It Geeks
    package_name: com.itgeeks.mobilify
    copyright_notice: Copyright © 2024 NT. All rights reserved.