enum Block_Name { // Views {
  // ButtomBarBlock,
  Image_Banner_Slider_Block,
  Image_Slider_Block, //simple
  Scrolling_Text_Block,
  Collection_Grid_Block,
  Product_Grid_Block,
  Count_Down_Timer_Block,
  Testimonials_Block,
  Image_Banner_Block,
  
  Divider_Block,
  Instagram_Feed_Block,
  Icon_Text_Block,
  Video_Block,
  Search_Block,
  Comparison_Block,
  Discount_Section_Block,
  Form_Block,
  Image_Only,
  Text_Only,
  Social_Media_Links,
  Text_with_background_Image,
  Image_Gird,
  Text_List,
  Blog_Slider,
  Button_Only,
  FAQ,
  Featured_Collection,
  Mailchimp_Subscription_Forms,
  Klaviyo_Subscription_Forms,
  Rebuy_Trending_Product,
  Rebuy_Recommended_Product,
  Rebuy_Quick_View,
  Rebuy_Top_Seller,
  Recent_Order_Theme_Third,
  Smile_io,
  Custom_Section,
  Text_Grid

  // BannerImageView,
  // BannerTextView,
  // BannerTextSubtitle,
  // BannerButtonTextView,
  // BannerVideoView,
  // FAQView,
  // ProductView,
  // CategoryView,
  // TextTileView,

  // GridView,
  // WebView
}
