enum SettingsEnum {
  App_Exclusive_Discounts,
  // App_Exclusive_Product_And_Collection,
  Localization,
  Product_Recommendations,
  // White_Label_App,
  Recently_Viewed_List,
  Customizable_Font,
  Product_Search_And_Sort,
  // Mobile_App_Promotion_Banner,
  // App_User_Discounts,
  // Social_Login,
  Smart_Search_Suggestions,
  Maintenance_Mode,
  Currency_Format,
  Guest_Checkout,
  Change_Default_Language,
  Auto_Navigate_To_Cart_Page,
  // Auto_Select_Variants,
  Variant_Specific_Images,
  Display_Vendor_Or_Brand,
  Display_SKU,
  Hide_Out_Of_Stock_Products,
  Display_Price_One_Below_The_Other,
  // Show_Vendor_Name,
  Show_Discount_Percentage,
  // Skip_Login_and_Address,
  // Order_Note,
  Minimum_Cart_Value,
  Disable_Checkout,
  Show_Filter_On_Product_List_Page,
  // Show_Stickers_On_Product_Cell
  Show_Intro_Screen_At_App_Start,
}
