  # name: Build Signed Android App Bundle

  # on:
  #   push:
  #     branches:
  #       - staging
  #   pull_request:
  #     branches:
  #       - staging

  # jobs:
  #   build:
  #     runs-on: windows-latest

  #     steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v2

  #       - name: Decode and save keystore
  #         run: |
  #           echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks
  #         shell: bash

  #       - name: Set up Flutter
  #         uses: subosito/flutter-action@v2
  #         # with:
  #         #   flutter-version: 'stable'

  #       - name: Flutter doctor
  #         run: flutter doctor
          
  #       - name: Flutter clean
  #         run: flutter clean

  #       - name: Flutter dependencies Upgrade
  #         run: flutter pub upgrade --major-versions

  #       # Install your project's dependencies
  #       - name: Install Flutter dependencies
  #         run: flutter pub get



  #       - name: Build Android App Bundle
  #         env:
  #           KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  #           KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  #           KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  #           ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/app/my-release-key.jks
  #         run: flutter build appbundle --release

  #       - name: Upload AAB
  #         uses: actions/upload-artifact@v3
  #         with:
  #           name: android-app-bundle
  #           path: build/app/outputs/bundle/release/app-release.aab
            
